server: 
  port: 21000
  address: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/service_management?characterEncoding=utf8&serverTimezone=UTC
    #username: sm
    #password: password
    url: jdbc:mysql://localhost:3306/wecube_core_01?characterEncoding=utf8&serverTimezone=UTC
    username: username
    password: password

  banner:
    location: classpath:/banner.txt

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    open-in-view: false
service:
  management: 
    httpclient:
      max-total-connections: 200
