server: 
  port: 21000
  address: localhost
  servlet:
    context-path: /service-mgmt
    
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-server:port/database-name?characterEncoding=utf8&serverTimezone=UTC
    username: db-user
    password: db-password

  banner:
    location: classpath:/banner.txt

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    open-in-view: false

service:
  management: 
    httpclient:
      max-total-connections: 200
    wecube-core-address: localhost:8080
    wecube-platform-token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJIVFRQLU1PQ0siLCJpYXQiOjE1NzYwNTMxOTcsInR5cGUiOiJhY2Nlc3NUb2tlbiIsImNsaWVudFR5cGUiOiJTVUJfU1lTVEVNIiwiZXhwIjoxNjAxOTczMTk3LCJhdXRob3JpdHkiOiJbU1VCX1NZU1RFTV0ifQ.Wd5rhFX3G-dtqlqYzgnkzd9i8T0xJkkPQSAckzO3V3NWXMCw3B9JWe7JlMjbNtE7va8qce1qcrz6qaa4pB0t5A
    s3-endpoint: http://127.0.0.1:9000
    s3-access-key: access_key
    s3-secret-key: secret_key
    s3-default-bucket: service-mgmt 
    system-code: SYS_SRV_MGMT

logging:
  level:
    root: info
