server: 
  port: 21000
  address: localhost
    
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-server:port/database-name?characterEncoding=utf8&serverTimezone=UTC
    username: db-user
    password: db-password

  banner:
    location: classpath:/banner.txt

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    open-in-view: false
service:
  management: 
    httpclient:
      max-total-connections: 200
